# mysql databases memory size in mb [database list from show database]
MYSQL_SCHEMAS_SIZE_MB = "SELECT table_schema, IFNULL(SUM(data_length+index_length)/1024/1024,0) AS total_size_mb, IFNULL(SUM(index_length)/1024/1024,0) AS index_size_mb, IFNULL(SUM(data_length)/1024/1024,0) AS data_size_byt, count(*) AS table_count FROM information_schema.tables GROUP BY table_schema"

# mysql database's table index size and data size in mb excluding mysql, performance_schema, information_schema database's tables
MYSQL_DBS_TABLE_I_D_SIZE_MB = "SELECT table_schema, table_name, IFNULL(index_length/1024/1024,0) AS index_size_mb, IFNULL(data_length/1024/1024,0) AS data_size_byt FROM information_schema.tables WHERE table_schema not in ('mysql', 'performance_schema', 'information_schema')"

# mysql system database's table index size and data size in mb [mysql, performance_schema, information_schema]
MYSQL_SYSTEM_DBS_TABLE_I_D_SIZE_MB = "SELECT table_schema, table_name, IFNULL(index_length/1024/1024,0) AS index_size_mb, IFNULL(data_length/1024/1024,0) AS data_size_byt FROM information_schema.tables WHERE table_schema in ('mysql', 'performance_schema', 'information_schema')"

# mysql system database's average query execution time in micro second
MYSQL_SCHEMAS_AVG_QUERY_EXE_TIME_MS = "SELECT schema_name, ROUND((SUM(sum_timer_wait) / SUM(count_star)) / 1000000) AS avg_us FROM performance_schema.events_statements_summary_by_digest WHERE schema_name IS NOT NULL GROUP BY schema_name"

# mysql innodb support status enabled/disabled
MYSQL_ENGINE_STATUS = "SELECT ENGINE, SUPPORT, TRANSACTIONS, SAVEPOINTS FROM information_schema.ENGINES WHERE engine IN ('InnoDB','MyISAM','PERFORMANCE_SCHEMA')"

# mysql innodb data collection query [if no data present in in this query -> possibly mysql instance must be AWS Aurora instance
MYSQL_INNODB_DATA = "SHOW /*!50000 ENGINE*/ INNODB STATUS"

# check whether the mysql instance is an AWS Aurora database
MYSQL_IS_AWS_AURORA = "SHOW VARIABLES LIKE 'aurora_server_id'"

# mysql global status metrics [performance, net, myisam]
MYSQL_SHOW_GLOBAL_STATUS = "SHOW GLOBAL STATUS"

# mysql global variables metrics [myisam, performance, connections]
MYSQL_SHOW_GLOBAL_VARIABLES = "SHOW GLOBAL VARIABLES"

MYSQL_VERSION_QUERY_RG = "SHOW GLOBAL VARIABLES WHERE variable_name = 'version'"

# mysql session metrics
MYSQL_SESSION_METRICS = "SELECT thd_id, pid, state, user, db, program_name, current_memory/1024 as current_memory_kb, statement_latency/1000000000 as cpu_time_ms, command, current_statement, lock_latency/1000000000 as lock_latency_ms, last_statement as last_query, last_statement_latency/1000000000 as last_query_cpu_ms from sys.x$session"

# mysql slow queries metrics
MYSQL_SLOW_QUERY = "SELECT ID, USER, HOST, DB, COMMAND, TIME, STATE, INFO FROM INFORMATION_SCHEMA.PROCESSLIST where time>{} and command<>'Sleep'"

# mysql top queries metrics
MYSQL_TOP_CPU_QUERY = "SELECT db, exec_count, err_count, warn_count, total_latency/1000000000 as total_latency, max_latency/1000000000 as max_latency, avg_latency/1000000000 as avg_latency, lock_latency/1000000000 as lock_latency, first_seen, last_seen, query from sys.x$statement_analysis order by avg_latency desc limit 10"

# mysql top queries metrics
MYSQL_REPLICATION_SLAVE_STATUS_QUERY = "SHOW SLAVE STATUS"

MYSQL_REPLICATION_MASTER_STATUS_QUERY = "SHOW MASTER STATUS"

# mysql top queries metrics
MYSQL_REPLICATION_GRP_MEMBERS_DATA_QUERY = "SELECT t1.CHANNEL_NAME,t1.MEMBER_ID,t1.MEMBER_HOST,t1.MEMBER_PORT,t1.MEMBER_STATE,t1.MEMBER_ROLE,t1.MEMBER_VERSION,t2.COUNT_TRANSACTIONS_IN_QUEUE,t2.COUNT_TRANSACTIONS_CHECKED,t2.COUNT_CONFLICTS_DETECTED,t2.COUNT_TRANSACTIONS_ROWS_VALIDATING,t2.COUNT_TRANSACTIONS_REMOTE_APPLIED,t2.COUNT_TRANSACTIONS_LOCAL_PROPOSED,t2.COUNT_TRANSACTIONS_LOCAL_ROLLBACK FROM performance_schema.replication_group_members t1, performance_schema.replication_group_member_stats t2 where t1.MEMBER_ID = t2.MEMBER_ID"

# metrics collected from MYSQL_SHOW_STATUS
MYSQL_GLOBAL_STATUS_GROUPING = {
    'Aborted_clients': ['ACL', 'perf'],
    'Aborted_connects': ['ACN', 'perf'],
    'Binlog_cache_disk_use': ['BCDU', 'perf'],
    'Binlog_cache_use': ['BCU', 'perf'],
    'Binlog_stmt_cache_disk_use': ['BSCDU', 'perf'],
    'Binlog_stmt_cache_use': ['BSCU', 'perf'],
    'Bytes_received': ['BR', 'perf'],
    'Bytes_sent': ['BS', 'perf'],
    'Com_alter_table': ['CAT', 'perf'],
    'Com_begin': ['CBN', 'perf'],
    'Com_binlog': ['CB', 'perf'],
    'Com_change_master': ['CCM', 'perf'],
    'Com_create_db': ['CCD', 'perf'],
    'Com_delete': ['CD', 'perf'],
    'Com_delete_multi': ['CDM', 'perf'],
    'Com_drop_db': ['CDD', 'perf'],
    'Com_drop_table': ['CDT', 'perf'],
    'Com_group_replication_start': ['CGRST', 'perf'],
    'Com_group_replication_stop': ['CGRSP', 'perf'],
    'Com_insert': ['CI', 'perf'],
    'Com_insert_select': ['CIS', 'perf'],
    'Com_load': ['CL', 'perf'],
    'Com_replace': ['CRP', 'perf'],
    'Com_replace_select': ['CRS', 'perf'],
    'Com_revoke': ['CRV', 'perf'],
    'Com_revoke_all': ['CRVA', 'perf'],
    'Com_rollback': ['CRB', 'perf'],
    'Com_rollback_to_savepoint': ['CRBTS', 'perf'],
    'Com_savepoint': ['CSP', 'perf'],
    'Com_select': ['CS', 'perf'],
    'Com_show_binlog_events': ['CSBE', 'perf'],
    'Com_show_binlogs': ['CSB', 'perf'],
    'Com_shutdown': ['CSD', 'perf'],
    'Com_slave_start': ['CSST', 'perf'],
    'Com_slave_stop': ['CSSP', 'perf'],
    'Com_stmt_execute': ['CSE', 'perf'],
    'Com_update': ['CU', 'perf'],
    'Com_update_multi': ['CUM', 'perf'],
    'Connections': ['CN', 'perf'],
    'Created_tmp_disk_tables': ['CTDT', 'perf'],
    'Created_tmp_files': ['CTF', 'perf'],
    'Created_tmp_tables': ['CTT', 'perf'],
    'Handler_commit': ['HC', 'perf'],
    'Handler_delete': ['HDT', 'perf'],
    'Handler_discover': ['HDS', 'perf'],
    'Handler_external_lock': ['HEL', 'perf'],
    'Handler_prepare': ['HPR', 'perf'],
    'Handler_read_first': ['HRF', 'perf'],
    'Handler_read_key': ['HRK', 'perf'],
    'Handler_read_last': ['HRL', 'perf'],
    'Handler_read_next': ['HRN', 'perf'],
    'Handler_read_prev': ['HRP', 'perf'],
    'Handler_read_rnd': ['HRR', 'perf'],
    'Handler_read_rnd_next': ['HRRN', 'perf'],
    'Handler_rollback': ['HR', 'perf'],
    'Handler_savepoint': ['HSP', 'perf'],
    'Handler_savepoint_rollback': ['HSPR', 'perf'],
    'Handler_update': ['HU', 'perf'],
    'Handler_write': ['HW', 'perf'],
    'Innodb_buffer_pool_bytes_data': ['IBPBDT', 'perf'],
    'Innodb_buffer_pool_bytes_dirty': ['IBPBDY', 'perf'],
    'Innodb_buffer_pool_pages_data': ['IBPPDT', 'perf'],
    'Innodb_buffer_pool_pages_dirty': ['IBPPDY', 'perf'],
    'Innodb_buffer_pool_pages_flushed': ['IBPPFL', 'perf'],
    'Innodb_buffer_pool_pages_total': ['IBPPT', 'perf'],
    'Innodb_buffer_pool_read_requests': ['IBPRR', 'perf'],
    'Innodb_buffer_pool_reads': ['IBPR', 'perf'],
    'Innodb_buffer_pool_wait_free': ['IBPWF', 'perf'],
    'Innodb_buffer_pool_write_requests': ['IBPWR', 'perf'],
    'Innodb_data_fsyncs': ['IDF', 'perf'],
    'Innodb_data_read': ['IDR', 'perf'],
    'Innodb_data_reads': ['IDRS', 'perf'],
    'Innodb_data_writes': ['IDWS', 'perf'],
    'Innodb_data_written': ['IDWN', 'perf'],
    'Innodb_log_write_requests': ['ILWR', 'perf'],
    'Innodb_log_writes': ['ILW', 'perf'],
    'Innodb_os_log_fsyncs': ['IOLF', 'perf'],
    'Innodb_page_size': ['IPS', 'perf'],
    'Innodb_pages_created': ['IPC', 'perf'],
    'Innodb_pages_read': ['IPR', 'perf'],
    'Innodb_pages_written': ['IPW', 'perf'],
    'Innodb_row_lock_current_waits': ['IRLCW', 'perf'],
    'Innodb_row_lock_time': ['IRLT', 'perf'],
    'Innodb_row_lock_waits': ['IRLW', 'perf'],
    'Innodb_rows_deleted': ['IRD', 'perf'],
    'Innodb_rows_inserted': ['IRI', 'perf'],
    'Innodb_rows_read': ['IRR', 'perf'],
    'Innodb_rows_updated': ['IRU', 'perf'],
    'Key_blocks_used': ['KBU', 'perf'],
    'Key_buffer_bytes_unflushed': ['KBBUF', 'perf'],
    'Key_buffer_bytes_used': ['KBBUS', 'perf'],
    'Key_read_requests': ['KRR', 'perf'],
    'Key_reads': ['KR', 'perf'],
    'Key_write_requests': ['KWR', 'perf'],
    'Key_writes': ['KW', 'perf'],
    'Max_used_connections': ['MUC', 'perf'],
    'Max_used_connections_time': ['MUCT', 'perf'],
    'Open_files': ['OF', 'perf'],
    'Open_streams': ['OS', 'perf'],
    'Open_table_definitions': ['OTD', 'perf'],
    'Open_tables': ['OT', 'perf'],
    'Qcache_free_blocks': ['QFB', 'perf'],
    'Qcache_free_memory': ['QFM', 'perf'],
    'Qcache_hits': ['QH', 'perf'],
    'Qcache_inserts': ['QI', 'perf'],
    'Qcache_lowmem_prunes': ['QLP', 'perf'],
    'Qcache_not_cached': ['QNC', 'perf'],
    'Qcache_queries_in_cache': ['QQIC', 'perf'],
    'Queries': ['QR', 'perf'],
    'Questions': ['QS', 'perf'],
    'Select_full_join': ['SFJ', 'perf'],
    'Select_scan': ['SS', 'perf'],
    'Slave_open_temp_tables': ['SOTT', 'perf'],
    'Slow_queries': ['SQ', 'perf'],
    'Sort_merge_passes': ['SMP', 'perf'],
    'Sort_range': ['SRG', 'perf'],
    'Sort_rows': ['SRW', 'perf'],
    'Sort_scan': ['SSC', 'perf'],
    'Table_locks_immediate': ['TLI', 'perf'],
    'Table_locks_waited': ['TLW', 'perf'],
    'Table_locks_waited_rate': ['TLWR', 'perf'],
    'Table_open_cache_hits': ['TOCH', 'perf'],
    'Table_open_cache_misses': ['TOCM', 'perf'],
    'Table_open_cache_overflows': ['TOCO', 'perf'],
    'Threads_cached': ['TCH', 'perf'],
    'Threads_connected': ['TCN', 'perf'],
    'Threads_created': ['TCR', 'perf'],
    'Threads_running': ['TR', 'perf'],
    'Uptime': ['UT', 'perf'],
    'Uptime_since_flush_status': ['UTSFS', 'perf'],
}

# '': ['', ''],

MYSQL_GLOBAL_VARIABLES_GROUPING = {
    'auto_generate_certs': ['AGC', 'conf'],
    'auto_increment_increment': ['AII', 'conf'],
    'auto_increment_offset': ['AIO', 'conf'],
    'autocommit': ['AC', 'conf'],
    'automatic_sp_privileges': ['ASP', 'conf'],
    'back_log': ['BL', 'conf'],
    'basedir': ['BD', 'conf'],
    'big_tables': ['BT', 'conf'],
    'binlog_cache_size': ['BCS', 'conf'],
    'binlog_encryption': ['BE', 'conf'],
    'binlog_error_action': ['BEA', 'conf'],
    'binlog_expire_logs_seconds': ['BELS', 'conf'],
    'binlog_format': ['BF', 'conf'],
    'binlog_gtid_simple_recovery': ['BGSR', 'conf'],
    'binlog_stmt_cache_size': ['BSCS', 'conf'],
    'bulk_insert_buffer_size': ['BIBS', 'conf'],
    'check_proxy_users': ['CPU', 'conf'],
    'connect_timeout': ['CT', 'conf'],
    'datadir': ['DD', 'conf'],
    'datetime_format': ['DF', 'conf'],
    'default_storage_engine': ['DSE', 'conf'],
    'default_tmp_storage_engine': ['DTSE', 'conf'],
    'delayed_insert_limit': ['DIL', 'conf'],
    'delayed_insert_timeout': ['DIT', 'conf'],
    'delayed_queue_size': ['DQS', 'conf'],
    'expire_logs_days': ['ELD', 'conf'],
    'general_log': ['GL', 'conf'],
    'general_log_file': ['GLF', 'conf'],
    'hostname': ['HN', 'conf'],
    'init_slave': ['IS', 'conf'],
    'innodb_autoinc_lock_mode': ['IALM', 'conf'],
    'innodb_buffer_pool_filename': ['IBPF', 'conf'],
    'innodb_buffer_pool_instances': ['IBPI', 'conf'],
    'innodb_buffer_pool_size': ['IBPS', 'conf'],
    'innodb_change_buffering': ['ICB', 'conf'],
    'innodb_data_file_path': ['IDFP', 'conf'],
    'innodb_data_home_dir': ['IDHD', 'conf'],
    'innodb_deadlock_detect': ['IDD', 'conf'],
    'innodb_flush_log_at_timeout': ['IFLAT', 'conf'],
    'innodb_flush_log_at_trx_commit': ['IFLATC', 'conf'],
    'innodb_io_capacity': ['IIC', 'conf'],
    'innodb_lock_wait_timeout': ['ILWT', 'conf'],
    'innodb_log_buffer_size': ['ILBS', 'conf'],
    'innodb_log_file_size': ['ILFS', 'conf'],
    'innodb_log_group_home_dir': ['ILGHD', 'conf'],
    'innodb_open_files': ['IOF', 'conf'],
    'innodb_replication_delay': ['IRPD', 'conf'],
    'innodb_rollback_on_timeout': ['IROT', 'conf'],
    'innodb_temp_data_file_path': ['ITDFP', 'conf'],
    'innodb_version': ['IV', 'conf'],
    'interactive_timeout': ['IT', 'conf'],
    'join_buffer_size': ['JBS', 'conf'],
    'key_buffer_size': ['KBS', 'conf'],
    'key_cache_age_threshold': ['KCAT', 'conf'],
    'key_cache_block_size': ['KCBS', 'conf'],
    'key_cache_division_limit': ['KCDL', 'conf'],
    'large_files_support': ['LFS', 'conf'],
    'large_page_size': ['LPS', 'conf'],
    'lock_wait_timeout': ['LWT', 'conf'],
    'log_bin': ['LB', 'conf'],
    'log_bin_basename': ['LBB', 'conf'],
    'log_bin_index': ['LBI', 'conf'],
    'log_error': ['LE', 'conf'],
    'long_query_time': ['LQT', 'conf'],
    'max_allowed_packet': ['MAP', 'conf'],
    'max_binlog_cache_size': ['MBCS', 'conf'],
    'max_binlog_size': ['MBS', 'conf'],
    'max_binlog_stmt_cache_size': ['MBSCS', 'conf'],
    'max_connect_errors': ['MCE', 'conf'],
    'max_connections': ['MC', 'conf'],
    'max_delayed_threads': ['MDT', 'conf'],
    'max_error_count': ['MEC', 'conf'],
    'max_heap_table_size': ['MHTS', 'conf'],
    'max_insert_delayed_threads': ['MIDT', 'conf'],
    'max_join_size': ['MJS', 'conf'],
    'max_prepared_stmt_count': ['MPSC', 'conf'],
    'max_sp_recursion_depth': ['MSRD', 'conf'],
    'max_tmp_tables': ['MTT', 'conf'],
    'max_user_connections': ['MUSC', 'conf'],
    'max_write_lock_count': ['MWLC', 'conf'],
    'myisam_data_pointer_size': ['MDPS', 'conf'],
    'myisam_max_sort_file_size': ['MMSFS', 'conf'],
    'myisam_mmap_size': ['MMS', 'conf'],
    'myisam_recover_options': ['MRO', 'conf'],
    'myisam_repair_threads': ['MRT', 'conf'],
    'myisam_sort_buffer_size': ['MSBS', 'conf'],
    'myisam_stats_method': ['MSM', 'conf'],
    'myisam_use_mmap': ['MUM', 'conf'],
    'net_buffer_length': ['NBL', 'conf'],
    'net_read_timeout': ['NRT', 'conf'],
    'net_retry_count': ['NRC', 'conf'],
    'net_write_timeout': ['NWT', 'conf'],
    'open_files_limit': ['OFL', 'conf'],
    'performance_schema': ['PS', 'conf'],
    'pid_file': ['PDF', 'conf'],
    'plugin_dir': ['PLD', 'conf'],
    'port': ['PT', 'conf'],
    'preload_buffer_size': ['PBS', 'conf'],
    'profiling_history_size': ['PHS', 'conf'],
    'query_alloc_block_size': ['QABS', 'conf'],
    'query_cache_size': ['QCS', 'conf'],
    'query_prealloc_size': ['QPS', 'conf'],
    'range_alloc_block_size': ['RABS', 'conf'],
    'read_buffer_size': ['RBS', 'conf'],
    'read_rnd_buffer_size': ['RRBS', 'conf'],
    'server_uuid': ['SU', 'conf'],
    'slow_query_log': ['SQL', 'conf'],
    'slow_query_log_file': ['SQLF', 'conf'],
    'socket': ['SK', 'conf'],
    'sort_buffer_size': ['SBFS', 'conf'],
    'sql_auto_is_null': ['SAIN', 'conf'],
    'sql_big_selects': ['SBSL', 'conf'],
    'sql_buffer_result': ['SBR', 'conf'],
    'sql_log_off': ['SLO', 'conf'],
    'sql_safe_updates': ['SSU', 'conf'],
    'sql_select_limit': ['SSL', 'conf'],
    'sql_warnings': ['SW', 'conf'],
    'sync_binlog': ['SB', 'conf'],
    'table_definition_cache': ['TDC', 'conf'],
    'table_open_cache': ['TOC', 'conf'],
    'thread_cache_size': ['TCS', 'conf'],
    'version': ['VR', 'conf'],
    'version_comment': ['VRC', 'conf'],
    'version_compile_machine': ['VCM', 'conf'],
    'version_compile_os': ['VCO', 'conf'],
    'wait_timeout': ['WT', 'conf'],
}

MYSQL_BASIC_INSIGHT_COMMON_VARIABLES = {
    'slow_query_log': None,
    'slow_query_log_file': None,
    'long_query_time': None,
}

MYSQL_INNODB_ENGINE_GROUPING = {
    'Innodb_active_transactions': ['IAT', 'perf'],
    'Innodb_buffer_pool_pages_free': ['IBPPF', 'perf'],
    'Innodb_current_transactions': ['ICT', 'perf'],
    'Innodb_hash_index_cells_total': ['IHICT', 'perf'],
    'Innodb_hash_index_cells_used': ['IHICU', 'perf'],
    'Innodb_history_list_length': ['IHLL', 'perf'],
    'Innodb_ibuf_free_list': ['IIFL', 'perf'],
    'Innodb_ibuf_merged': ['IIM', 'perf'],
    'Innodb_ibuf_merged_delete_marks': ['IIMDM', 'perf'],
    'Innodb_ibuf_merged_deletes': ['IIMD', 'perf'],
    'Innodb_ibuf_merged_inserts': ['IIMI', 'perf'],
    'Innodb_ibuf_merges': ['IIMS', 'perf'],
    'Innodb_ibuf_segment_size': ['IISS', 'perf'],
    'Innodb_ibuf_size': ['IIS', 'perf'],
    'Innodb_lock_structs': ['ILS', 'perf'],
    'Innodb_locked_tables': ['ILTB', 'perf'],
    'Innodb_locked_transactions': ['ILTR', 'perf'],
    'Innodb_lsn_current': ['ILC', 'perf'],
    'Innodb_lsn_flushed': ['ILF', 'perf'],
    'Innodb_lsn_last_checkpoint': ['ILLC', 'perf'],
    'Innodb_mem_adaptive_hash': ['IMAH', 'perf'],
    'Innodb_mem_additional_pool': ['IMAP', 'perf'],
    'Innodb_mem_dictionary': ['IMD', 'perf'],
    'Innodb_mem_file_system': ['IMFS', 'perf'],
    'Innodb_mem_lock_system': ['IMLS', 'perf'],
    'Innodb_mem_page_hash': ['IMPH', 'perf'],
    'Innodb_mem_recovery_system': ['IMRS', 'perf'],
    'Innodb_mem_thread_hash': ['IMTB', 'perf'],
    'Innodb_mem_total': ['IMT', 'perf'],
    'Innodb_mutex_os_waits': ['IMOW', 'perf'],
    'Innodb_mutex_spin_rounds': ['IMSR', 'perf'],
    'Innodb_mutex_spin_waits': ['IMSW', 'perf'],
    'Innodb_os_file_fsyncs': ['IOFF', 'perf'],
    'Innodb_os_file_reads': ['IOFR', 'perf'],
    'Innodb_os_file_writes': ['IOFW', 'perf'],
    'Innodb_pending_aio_log_ios': ['IPALI', 'perf'],
    'Innodb_pending_aio_sync_ios': ['IPASI', 'perf'],
    'Innodb_pending_buffer_pool_flushes': ['IPBPF', 'perf'],
    'Innodb_pending_checkpoint_writes': ['IPCW', 'perf'],
    'Innodb_pending_ibuf_aio_reads': ['IPIAR', 'perf'],
    'Innodb_pending_log_flushes': ['IPLF', 'perf'],
    'Innodb_pending_log_writes': ['IPLW', 'perf'],
    'Innodb_pending_normal_aio_reads': ['IPNAR', 'perf'],
    'Innodb_pending_normal_aio_writes': ['IPNAW', 'perf'],
    'Innodb_queries_inside': ['IQI', 'perf'],
    'Innodb_queries_queued': ['IQQ', 'perf'],
    'Innodb_read_views': ['IRV', 'perf'],
    'Innodb_s_lock_os_waits': ['ISLOW', 'perf'],
    'Innodb_s_lock_spin_rounds': ['ISLSR', 'perf'],
    'Innodb_s_lock_spin_waits': ['ISLSW', 'perf'],
    'Innodb_semaphore_waits': ['ISW', 'perf'],
    'Innodb_semaphore_wait_time': ['ISW', 'perf'],
    'Innodb_tables_in_use': ['ITIU', 'perf'],
    'Innodb_x_lock_os_waits': ['IXLOW', 'perf'],
    'Innodb_x_lock_spin_rounds': ['IXLSR', 'perf'],
    'Innodb_x_lock_spin_waits': ['IXLSW', 'perf'],
}

MYSQL_REPLICATION_STATUS_GROUPING = {
    'Slave_IO_State': ['SIS', 0],
    'Master_Host': ['MH', 1],
    'Master_User': ['MU', 2],
    'Master_Port': ['MP', 3],
    'Connect_Retry': ['CR', 4],
    'Master_Log_File': ['MLF', 5],
    'Read_Master_Log_Pos': ['RMLP', 6],
    'Relay_Log_File': ['RLF', 7],
    'Relay_Log_Pos': ['RLP', 8],
    'Relay_Master_Log_File': ['RMLF', 9],
    'Slave_IO_Running': ['SIR', 10],
    'Slave_SQL_Running': ['SSR', 11],
    'Seconds_Behind_Master': ['SBM', 32],
    'Master_UUID': ['MUUID', 40],
    'Master_Info_File': ['MIF', 41],
    'SQL_Delay': ['SD', 42],
    'Slave_SQL_Running_State': ['SSRS', 44],
}

MYSQL_REPLICATION_GRP_DATA_GROUPING = {
    'CHANNEL_NAME': ['RCN', 0],
    'MEMBER_ID': ['RMI', 1],
    'MEMBER_HOST': ['RMH', 2],
    'MEMBER_PORT': ['RMP', 3],
    'MEMBER_STATE': ['RMS', 4],
    'MEMBER_ROLE': ['RMR', 5],
    'MEMBER_VERSION': ['RMV', 6],
    'COUNT_TRANSACTIONS_IN_QUEUE': ['RCTIQ', 7],
    'COUNT_TRANSACTIONS_CHECKED': ['RCTC', 8],
    'COUNT_CONFLICTS_DETECTED': ['RCCD', 9],
    'COUNT_TRANSACTIONS_ROWS_VALIDATING': ['RCTRV', 10],
    'COUNT_TRANSACTIONS_REMOTE_APPLIED': ['RCTRA', 11],
    'COUNT_TRANSACTIONS_LOCAL_PROPOSED': ['RCTLP', 12],
    'COUNT_TRANSACTIONS_LOCAL_ROLLBACK': ['RCTLR', 13],
}