#!/bin/bash

#       NOTE :
#               Please do not edit this file, as it will be replaced during upgrade.


getMemoryDetails() {
	free -k | awk 'BEGIN {  
	        ORS="\n";
	}
	{
	        #print "Processing Record ",NR;
	        if (NR == 2)
	                print "TotalVisibleMemorySize :",$2
	        else if (NR == 3)
	                print "FreePhysicalMemory :",$4
	        else if (NR == 4)
	                print "TotalVirtualMemorySize :",$2,"\nFreeVirtualMemory :",$4          
	}'
	
	/bin/cat /etc/issue | awk 'BEGIN {  
	        ORS="\n";
	        LINUX_DIST="";
	}
	{
	        #print "Processing Record ",NR;
	        if (NR<6 && $0 != "") {
	                LINUX_DIST=LINUX_DIST""$0
	                gsub(/\\n/,"",LINUX_DIST)
	                gsub(/\\l/,"",LINUX_DIST)
	                gsub(/\\r/,"",LINUX_DIST)
	                gsub(/\\m/,"",LINUX_DIST)	                
	        }       
	}END {print "Linux Distribution : ",LINUX_DIST}'
}

getMemoryStats() {
	cat /proc/vmstat | grep -i 'pgpgin\|pgpgout\|pgfault'
}

main() {
	if [ "$1" == "mem_details" ]; then
		getMemoryDetails
	elif [ "$1" == "mem_stats" ]; then
		getMemoryStats
	fi
}

main $1

