#!/bin/bash

# NOTE :
#	 Please do not edit this file, as it will be replaced during upgrade.

# commands : mii-tool, ethtool, /bin/dmesg | grep -i duplex
#/sys/class/net/eth0/speed
#/sys/class/net/eth0/duplex
#if_status = 7 ==> down
#if_status = 2 ==> up
fetchTrafficDetails() {
	cat /proc/net/dev | awk 'BEGIN {
		ORS="\n";
	}
	{	
		#print "Processing Record ",NR,NF;
		if_name = ""
		rx_bytes = 0
		if (NR > 2) {
			split($1, temp_arr, ":")
			if_name = temp_arr[1]	
			if_speed = ""	
			sub(/[ \t]+$/,"",temp_arr[2])
			#print ":"temp_arr[2]":"
			if (temp_arr[2] == "")
			{
				rx_bytes = $2
				ifSpeed_command = "/bin/cat /sys/class/net/"if_name"/speedd"
				isStateCommandSuccess = (ifSpeed_command | getline if_speed)
				print if_name,rx_bytes,$3,$10,$11,$12,$13,"speed : ",if_speed;
			}
			else
			{
				rx_bytes = temp_arr[2]
				ifSpeed_command = "/bin/cat /sys/class/net/"if_name"/speed"
				isStateCommandSuccess = (ifSpeed_command | getline if_speed)
				print if_name,rx_bytes,$2,$9,$10,$11,$12,"speed : ",if_speed;
			}
		}		
	}'
}


fetchInterfaceStatus() {
	ls /sys/class/net/ | awk 'BEGIN {
		ORS="\n";
	}
	{
		#print $NF
		if_status = 7
		if_address = ""
		if_name = $NF		
		state_command = "/bin/cat /sys/class/net/"$NF"/operstate"
		macAddr_command = "/bin/cat /sys/class/net/"$NF"/address"
		isStateCommandSuccess = (state_command | getline if_state) 
		isMacAddrCommandSuccess = (macAddr_command | getline if_address)
		#print isStateCommandSuccess isMacAddrCommandSuccess
		#print "State : "if_state" Address : "if_address
		if (if_address != "")
		{
			if (if_state == "up")
			{
				if_status = 2
			}
			print if_name" -- "if_status" -- "if_address
		}
	}'
}


main() {
	if [ "$1" == "if_status" ]; then
		fetchInterfaceStatus
	elif [ "$1" == "if_traffic" ]; then
		fetchTrafficDetails
	fi
}

main $1
