#!/bin/bash

# NOTE :
#	 Please do not edit this file, as it will be replaced during upgrade.

osArchitecture() {
	uname -i | awk 'BEGIN {
		ORS="\n";
	}
	{	
		#print "Processing Record ",NR,NF,$NF;
		print "Architecture : "$NF
	}'	
}

osArchitecture
