#!/bin/bash

# NOTE :
#	 Please do not edit this file, as it will be replaced during upgrade.



installedSoftware() {
	dpkg --list | awk 'BEGIN {
		ORS="\n";
	}
	{
		if (NR > 5)	{
			description = "" 
			for(i=4;i<=NF;i++){description=description" "$i}; 
			print $2 " ::: " $3 " ::: "description
		}
	}'
}

apt_history(){
      case "$1" in
        install)
              cat /var/log/dpkg.log | grep 'install '
              ;;
        upgrade|remove)
              cat /var/log/dpkg.log | grep $1
              ;;
        rollback)
              cat /var/log/dpkg.log | grep upgrade | \
                  grep "$2" -A10000000 | \
                  grep "$3" -B10000000 | \
                  awk '{print $4"="$5}'
              ;;
        *)
              cat /var/log/dpkg.log
              ;;
      esac
}

# Debian packages
# To list all packages --> dpkg --list
# To know details about the package --> dpkg-query -p <package_name>

# RPM related packages
# To list all packages installed --> rpm -qa
# To know details about the package --> rpm -qi <package_name>


main() {
	#installedSoftware
	apt_history
}

main $1
