#!/bin/bash

# NOTE :
#	 Please do not edit this file, as it will be replaced during upgrade.

# http://unix.stackexchange.com/questions/72177/what-is-pts-0-and-0-0-in-linux-by-type-who-am-i


listUsers() {
	who -uH | awk 'BEGIN {
		ORS="\n";
	}
	{
		if (NR > 1)	{
			timeField = "" 
			for(i=4;i<=NF;i++){timeField=timeField" "$i}; 
			print $1 " ::: "$2" ::: "$3" "$4" ::: "$7
		}
	}'
}

lastLoggedInUsers() {
	last -F | head -n 20 | awk 'BEGIN {
		ORS="\n";
	}
	{
		timePeriod = "" 
		for(i=4;i<=NF;i++){timePeriod=timePeriod" "$i}; 
		print $1 " ::: "$2" ::: "$3" ::: "timePeriod
	}'
}

main() {
	#listUsers
	lastLoggedInUsers
}

main $1
